site_name: Microeconomics 
site_url: https://pharringtonp19.github.io/mecon/

nav: 
  - Home: index.md 
  - About: about.md
  - Chapters:
    - Chapter One: 'chapters/chapter1.ipynb'

theme:
  name: material

plugins:
    - search  # default search plugin; needs manually re-enabling when using any other plugins
    - autorefs  # Cross-links to headings
    - include_exclude_files:
        include:
        exclude:
            - "_overrides"
            - "_static/README.md"
    - mknotebooks  # Jupyter notebooks