site_name: Microeconomics 
site_url: https://pharringtonp19.github.io/mecon/
site_description: An undergraduate microeconimcs course
site_author: Patrick Power
nav: 
  - Overview:
      - Summary: index.md
      - Introduction: 'overview/overview.md'
      - Syllabus: 'overview/Syllabus.pdf'
  - Topics:
      - Optimization:
          - Introduction: 'chapters/optimization/introduction.md'
      - Probability Theory:
          - Introduction: 'chapters/probability theory/introduction.md'
      - Math on the Computer:
          - Introduction: 'chapters/math on the computer/introduction.md'
      - Real World Events:
          - Introduction: 'chapters/real world events/introduction.md'

      # - General Concepts:
      #   - Why Model? : 'chapters/why_model.md'
      #   - Uncertainty : 'chapters/constraints/uncertainty.md'
      #   - Solving Models: 'chapters/solving_models.md'
      #   - Notation: 'chapters/notation.md'
      #   - Learning: 'chapters/learning.md'
      # - Choice Sets:
      #   - Basics of Constraints: 'chapters/constraints/constraints_overview.md'
      #   - Budget Constraint: 'chapters/constraints/budget_contraints.md'
      #   - Real World Constraints: 'chapters/constraints/exploring_choice.md'
      # - Objectives:
      #   - Utility: 'chapters/objectives/utility.md'
      #   #- Random Utility: 'chapters/objectives/random_utility.md'
      #   - Production Function: 'chapters/objectives/production_constraints.md'
      #   - Profit: 'chapters/objectives/profit.md'
      # # - Solvers: 
      # #   - Intro: 'chapters/solvers/intro.md'
      # #   - Basics: 'chapters/solvers/stopping.md'
      # - Applications: 
      #   - Demand: 'chapters/applications/demand.md'
      #   - Comparative Statics: 'chapters/comparative_statics.md'
      #   - Game Theory: 'chapters/applications/game theory.md'
      # - Markets: 
      #   - Asymmetric Information: 'chapters/markets/information.md'
      #   - Asymmetric Information (2): 'chapters/html_scripts/compensation.html'
  - Slides:
      - Consumer Heterogeneity: 'chapters/slides/conumers.md'
      - Comparative Statics: 'chapters/slides/comparative_statics.md'
      - Optimal Policy: 'chapters/slides/optimal_policy.md'
      - Game Theory: 'chapters/slides/game_theory.md'
      - Choice Uncertainty: 'chapters/slides/choice_uncertainty.md'
      - Asymmetric Information: 'chapters/slides/asymmetric_information.md'
      - Optimization: 'chapters/slides/optimization.md'
      - Applications: 'chapters/slides/applications.md'
  - YouTube: 
      - Constraints: 'chapters/YouTube/constraints.md'
      - Teacher Supply: 'chapters/YouTube/teacher_supply.md'
  # - Math:
  #     - Functions: 'math/functions.md'
  #     - Partial Evaluation: 'math/partial_evaluation.md'
  #     # - Background for Optimization: 'math/opt1.md'
  #     - Local Minimum: 'math/local minimum.md'
  #     - Probability Introduction: 'math/probability_intro.md'


  # - Assignments: 
  #     # - Writing Exercise Example: 'Problem Sets/Writing Exercise.md'
  #     - PS1 : 'Problem Sets/Problem_Set_One.pdf'
  #     - PS1 Solutions: 'Problem Sets/Problem_Set_One_Solutions.pdf'
  #     - PS2 : 'Problem Sets/Problem_Set_Two.pdf'
  #     - PS2 Solutions: 'Problem Sets/Problem_Set_Two_Solutions.pdf'

  #     - Optimization:
  #       - Background: 'math/opt1.md'
      # - Probability:
        # - Conditional Expectations: 'math/conditional_expectations.md'
      # - Optimization Overview: 'math/opt2.ipynb'
      # - Gradient Descent: 'math/gradient_descent.ipynb'
      # - Newton's Method: 'math/newton method.ipynb'
      # - Convexity: 'math/convexity.ipynb'
  # - Other:
  #     - Terms : 'other/comp_terms.ipynb'
      # - Jax Basics: 'other/jax basics.ipynb'
      # - Symbolic Computation: 'other/symbolic computation.ipynb'
      # - Thoughts: 'other/thoughts.ipynb'
      



theme:
  name: material
  palette:
    scheme: default
    primary: deep purple
  icon:
    admonition:
      code: fontawesome/solid/code
      note: octicons/tag-16
  features:
    #- navigation.instant
    - navigation.tabs
    - navigation.indexes
    - toc.integrate
    - navigation.top


markdown_extensions:
    - codehilite
    - attr_list
    - md_in_html
    - pymdownx.superfences:
        custom_fences:
          - name: mermaid
            class: mermaid
            format: !!python/name:pymdownx.superfences.fence_code_format
    - admonition
    - pymdownx.details
    - pymdownx.arithmatex:  # Render LaTeX via MathJax
        generic: true
    - pymdownx.emoji:
        emoji_index: !!python/name:materialx.emoji.twemoji
        emoji_generator: !!python/name:materialx.emoji.to_svg
    - footnotes
    - def_list
    - pymdownx.tasklist:
        custom_checkbox: true


plugins:
  - search
  # - mknotebooks
  # - mkdocs-jupyter:
  #     ignore_h1_titles: True
  #     execute: False
  #     include_source: False

extra_javascript: 
    # The below three make MathJax work, see https://squidfunk.github.io/mkdocs-material/reference/mathjax/
    - _static/mathjax.js
    - https://polyfill.io/v3/polyfill.min.js?features=es6
    - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js