site_name: Microeconomics 
site_url: https://pharringtonp19.github.io/mecon/
site_description: An undergraduate microeconimcs course
site_author: Patrick Power
nav: 
  - EC201: index.md 
  - Overview:
    - Overview: 'overview/overview.md'
    - Syllabus: 'overview/Syllabus.pdf'
  - Notes:
      - General Concepts:
        - Why Model? : 'chapters/why_model.md'
        - Uncertainty : 'chapters/constraints/uncertainty.md'
        - Solving Models: 'chapters/solving_models.md'
      - Constraints:
        - Basics of Constraints: 'chapters/constraints/constraints_overview.md'
        - Budget Constraint: 'chapters/constraints/budget_contraints.md'
        - Real World Constraints: 'chapters/constraints/exploring_choice.md'
      - Objectives:
        - Utility: 'chapters/objectives/utility.md'
        - Production Function: 'chapters/objectives/production_constraints.md'
        - Profit: 'chapters/objectives/profit.md'
      - Solvers: 
        - Intro: 'chapters/solvers/intro.md'
        - Basics: 'chapters/solvers/stopping.md'
      - Applications: 
        - Demand: 'chapters/applications/demand.md'
        - Comparative Statics: 'chapters/comparative_statics.md'
  - Slides:
      - Consumer Heterogeneity: 'chapters/slides/conumers.md'
  - Math:
      - Functions: 'math/functions.md'
      - Partial Evaluation: 'math/partial_evaluation.md'
      # - Background for Optimization: 'math/opt1.md'
      - Basics of Optimization: 'math/opt2.md'
      # - Probability Introduction: 'math/probability_intro.md'
  - Assignments: 
      - Writing Exercise Example: 'Problem Sets/Writing Exercise.md'
      - PS1 : 'Problem Sets/Problem_Set_One.pdf'
      - PS2 : 'Problem Sets/Problem_Set_Two.pdf'
      - PS1 Solutions: 'Problem Sets/Problem_Set_One_Solutions.pdf'
      - PS2 Solutions: 'Problem Sets/Problem_Set_Two_Solutions.pdf'

  #     - Optimization:
  #       - Background: 'math/opt1.md'
      # - Probability:
        # - Conditional Expectations: 'math/conditional_expectations.md'
      # - Optimization Overview: 'math/opt2.ipynb'
      # - Gradient Descent: 'math/gradient_descent.ipynb'
      # - Newton's Method: 'math/newton method.ipynb'
      # - Convexity: 'math/convexity.ipynb'
  # - Other:
  #     - Terms : 'other/comp_terms.ipynb'
      # - Jax Basics: 'other/jax basics.ipynb'
      # - Symbolic Computation: 'other/symbolic computation.ipynb'
      # - Thoughts: 'other/thoughts.ipynb'
      



theme:
  name: material
  palette:
    scheme: default
    primary: deep purple
  icon:
    admonition:
      code: fontawesome/solid/code
      note: octicons/tag-16
  features:
    #- navigation.instant
    - navigation.tabs
    - navigation.indexes
    - toc.integrate
    - navigation.top


markdown_extensions:
    - codehilite
    - attr_list
    - md_in_html
    - pymdownx.superfences:
        custom_fences:
          - name: mermaid
            class: mermaid
            format: !!python/name:pymdownx.superfences.fence_code_format
    - admonition
    - pymdownx.details
    - pymdownx.arithmatex:  # Render LaTeX via MathJax
        generic: true
    - pymdownx.emoji:
        emoji_index: !!python/name:materialx.emoji.twemoji
        emoji_generator: !!python/name:materialx.emoji.to_svg
    - footnotes
    - def_list
    - pymdownx.tasklist:
        custom_checkbox: true


plugins:
  - search
  # - mknotebooks
  - mkdocs-jupyter:
      ignore_h1_titles: True
      execute: False
      include_source: False

extra_javascript: 
    # The below three make MathJax work, see https://squidfunk.github.io/mkdocs-material/reference/mathjax/
    - _static/mathjax.js
    - https://polyfill.io/v3/polyfill.min.js?features=es6
    - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js