site_name: Microeconomics 
site_url: https://pharringtonp19.github.io/mecon/
site_description: An undergraduate microeconimcs course

nav: 
  - Home: index.md 
  - About: about.md
  - Chapter One: chapter1.ipynb

theme:
  name: material

plugins:
  - search
  - mkdocs-jupyter