site_name: Microeconomics 
site_url: https://pharringtonp19.github.io/mecon/
site_description: An undergraduate microeconimcs course

nav: 
  - Home: index.md 
  - About: about.md
  - Chapters:
    - Chapter One: 'chapters/chapter1.ipynb'

theme:
  name: material

plugins:
  - mkdocs-jupyter:
    ignore_h1_titles: True
    execute: True