site_name: Microeconomics 
site_url: https://pharringtonp19.github.io/mecon/

nav: 
  - Home: index.md 
  - About: about.md
  - Chapters:
    - Chapter One: 'chapters/chapter1.ipynb'

theme:
  name: material